name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test
      - run: dotnet publish
      
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: ssh-keyscan 209.97.129.212 >> ~/.ssh/known_hosts

      - name: Stop Server   
        run: ssh -tt david2@209.97.129.212 'sudo /bin/systemctl stop manx-corpus.service'
        
      # This errors as it won't wipe above the directory specified (good)
      - name: Wipe site data
        run: ssh -tt david2@209.97.129.212 'rm -rf /var/www/manx-corpus/{*,.*}'
        continue-on-error: true
      
      - name: Pull and Copy Site Code
        run: ssh -tt david2@209.97.129.212 'cd ~/manx-corpus && git pull origin master && cp -r ~/manx-corpus /var/www/'
      
      - name: Pull and Copy Open Data
        run: ssh -tt david2@209.97.129.212 'cd ~/manx-search-data && git pull origin master && cp -r ~/manx-search-data/OpenData /var/www/manx-corpus/CorpusSearch'
      
      - name: Pull and Copy Private Data
        # TODO: Update:  && git pull origin master && 
        run: ssh -tt david2@209.97.129.212 'cd ~/corpus-search-data-private && cp -r ~/corpus-search-data-private/ClosedData /var/www/manx-corpus/CorpusSearch'
      
      - name: Build
        run: ssh -tt david2@209.97.129.212 'cd /var/www/manx-corpus/ && dotnet build'
      
      - name: Publish
        run: ssh -tt david2@209.97.129.212 'cd /var/www/manx-corpus/ && dotnet publish --configuration Release'

      - name: Upload Cregeen Dictionary
        run: ssh -tt david2@209.97.129.212 'cd /var/www/manx-corpus/CorpusSearch/bin/Release/net6.0/publish/Resources && /var/www/manx-corpus/.github/scripts/download_cregeen.sh'
        continue-on-error: true

      - name: Upload Kelly M2E Dictionary
        run: ssh -tt david2@209.97.129.212 'cd /var/www/manx-corpus/CorpusSearch/bin/Release/net6.0/publish/Resources && /var/www/manx-corpus/.github/scripts/download_kelly_m2e.sh'
        continue-on-error: true
        
      - name: Restart Service
        run: ssh -tt david2@209.97.129.212 'sudo /bin/systemctl start manx-corpus.service'
